# Generated by Django 4.0.6 on 2022-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_firstname_user_lastname_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dabadebis_dge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dabadebis_tve',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dabadebis_weli',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qalaqi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qveyana',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telefonis_nomeri',
            field=models.IntegerField(null=True),
        ),
    ]
