# Generated by Django 4.0.6 on 2022-09-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_dabadebis_dge_user_dabadebis_tve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dasturi',
        ),
    ]
