# Generated by Django 4.0.6 on 2022-09-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_product_dasturi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dasturi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
